config/routes.rb
Rails.application.routes.draw do
  root 'page#index'

  devise_for :users, path: "acesso", path_names: { sign_up: 'cadastrar', sign_in: 'entrar', sign_out: 'sair', password: 'secret' }

  scope(path_names: { new: 'novo', edit: 'editar', show: 'ver' }) do
    resources :people
    resources :users
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can [:read, :update, :destroy], Person
      can :manage, User
    end
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Pessoa criada com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Pessoa editada com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Pessoa excluída com sucesso.' }
    end
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuário editado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário excluído com sucesso.' }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:admin, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gerentao</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- icons font-awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
</head>
<body>

<%= yield %>

</body>
</html>

app/views/page/index.html.erb
<nav class="light-blue lighten-1" role="navigation">
  <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
      <% else %>
        <li>
        <%= link_to('Login', new_user_session_path)  %>
        </li>
      <% end %>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h2 class="header center orange-text">Gerentão, Prazer!</h2>
    <div class="row center">
      <h5 class="header col s12 light">Coloco a casa pra funcionar!</h5>
    </div>
    <div class="row center">
      <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light orange">Vem cmg</a>
    </div>
    <br><br>

  </div>
</div>


<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Código versionado!</h5>

          <p class="light">Desde os primeiros passos tenha seu código organizado e seguro.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
          <h5 class="center">Código containerizado!</h5>

          <p class="light">Nada mais chato que ficar configurando máquinas virtuais para rodar serviços que na maioria nem são usados. Para de quebrar a cabeça com serviços de hospedagem porcaria.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Código Testado!</h5>

          <p class="light">Trabalhe com confiança e coragem. Testes garantirão a evolução sustentável do seu código.</p>
        </div>
      </div>
    </div>

  </div>
  <br><br>
</div>

<footer class="page-footer orange">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Company Bio</h5>
        <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Settings</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Connect</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
    </div>
  </div>
</footer>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= button_tag t('view.submit_action_html', model_name: ''), type: 'submit', class: "btn-xs btn-primary btn" %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editar pessoa</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @person %> |
<%= link_to 'Voltar', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de pessoas</h1>

<table>
  <thead>
    <tr>
      <th><%= Person.human_attribute_name('name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, person, title: t('view.view_action_hint', model_name: Person.model_name.human) %></td>
        <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_person_path(person), title: t('view.edit_action_hint', model_name: Person.model_name.human) %></td>
        <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, person, method: :delete, data: { confirm: t('view.delete_action_confirmation', model_name: Person.model_name.human) }, title: t('view.delete_action_hint', model_name: Person.model_name.human) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('view.new_action_html', model_name: Person.model_name.human), new_person_path, class: "btn btn-primary" %>

app/views/people/new.html.erb
<h1>Nova pessoa</h1>

<%= render 'form' %>

<%= link_to 'Voltar', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Person.human_attribute_name('name') %>:</strong>
  <%= @person.name %>
</p>

<%= link_to 'Editar', edit_person_path(@person) %> |
<%= link_to 'Voltar', people_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= button_tag t('view.submit_action_html', model_name: ''), type: 'submit', class: "btn-xs btn-primary btn" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editar usuário</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @user %> |
<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de usuários</h1>

<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name('admin') %></th>
      <th><%= User.human_attribute_name('name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.admin %></td>
        <td><%= user.name %></td>
        <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, user, title: t('view.view_action_hint', model_name: User.model_name.human) %></td>
        <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_user_path(user), title: t('view.edit_action_hint', model_name: User.model_name.human) %></td>
        <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, user, method: :delete, data: { confirm: t('view.delete_action_confirmation', model_name: User.model_name.human) }, title: t('view.delete_action_hint', model_name: User.model_name.human) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('view.new_action_html', model_name: User.model_name.human), new_user_path, class: "btn btn-primary" %>

app/views/users/new.html.erb
<h1>Novo usuário</h1>

<%= render 'form' %>

<%= link_to 'Voltar', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= User.human_attribute_name('admin') %>:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong><%= User.human_attribute_name('name') %>:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>